version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3300:3300"
    environment:
      - DEV_DB_HOST=postgresdb
      - DEV_DB_USERNAME=$POSTGRESDB_USER
      - DEV_DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DEV_DATABASE_URL=$POSTGRESDB_DATABASE
      - DEV_DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db: